---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
enabled: true
useGitignore: true
ignorePaths:
  - .config/ansible-lint-ignore.txt
  - .config/ansible-lint.yaml
  - .config/requirements*
  - \.*
  - cspell.config.yaml
  - pyproject.toml # ported [tool.pylint] disable-list comments are mostly English words

languageSettings:
  - languageId: python
    allowCompoundWords: false
