collections:
  - name: ansible.posix # docker
    version: ">=1.4.0"
  - name: google.cloud
  - name: amazon.aws
  - name: community.docker
    version: ">=3.10.2"
  - name: containers.podman
  - name: azure.azcollection
    version: ">=1,<2"
  - name: community.crypto
    version: ">=1.8.0"
  - name: community.vagrant
  - name: openstack.cloud
