collections:
  - name: ansible.posix # docker
    version: ">=1.4.0"
  - name: google.cloud
  - name: amazon.aws
  - name: community.docker
    version: ">=3.10.2"
  - name: containers.podman
  - name: azure.azcollection
    version: ">=1,<2"
  - name: community.crypto
    version: ">=1.8.0"
  # Workaround since https://github.com/ansible-community/molecule-plugins/issues/301#issuecomment-2675066085 is fixed
  # - name: community.vagrant
  - git+https://github.com/apatard/community.vagrant.git,initial-import
  - name: openstack.cloud
