---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Get Lima instance list
      ansible.builtin.command: limactl list --format json
      register: lima_list
      changed_when: false

    - name: Parse Lima instance list
      ansible.builtin.set_fact:
        lima_instances: "{{ lima_list.stdout_lines | map('from_json') | list }}"

    - name: Delete Lima VMs
      ansible.builtin.command: limactl delete --force {{ item.name }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name in lima_instances | map(attribute='name') | list
      changed_when: true

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
